services:
  db:
    image: pgvector/pgvector:pg16
    container_name: docuchat_db
    environment:
      POSTGRES_DB: docuchat
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: docuchat_backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: docuchat
      DB_USER: admin
      DB_PASSWORD: admin
      GROQ_API_KEY: ${GROQ_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: docuchat_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata: